name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Build executables
      run: |
        # Show current directory and structure
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        dir
        echo "CMD directory contents:"
        dir cmd
        
        # Build devproxy
        go build -v -o devproxy.exe ./cmd/devproxy
        
        # Build devctl
        go build -v -o devctl.exe ./cmd/devctl
        
        # Build devproxy-tray
        go build -v -ldflags="-H windowsgui" -o devproxy-tray.exe ./cmd/devproxy-tray
        
        # Verify builds
        echo "Built files:"
        dir *.exe
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          devproxy.exe
          devctl.exe
          devproxy-tray.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}